language: objective-c
before_install:
- brew tap AdoptOpenJDK/openjdk
- brew cask install adoptopenjdk8
- ls /Library/Java/JavaVirtualMachines/
- export JAVA_HOME=/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home
- wget http://dl.google.com/android/android-sdk_r24.4.1-macosx.zip
- unzip android-sdk_r24.4.1-macosx.zip
- export ANDROID_HOME=$PWD/android-sdk-macosx
- export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
- echo yes | android update sdk --filter platform-tools --no-ui --force > /dev/null
- echo yes | android update sdk --filter android-28 --no-ui --force > /dev/null
- echo yes | android update sdk --filter android-29 --no-ui --force > /dev/null
- echo yes | android update sdk --filter build-tools-28.0.3 --all --no-ui --force > /dev/null
install:
- nvm install v12.18.0 --reinstall-packages-from=node
- npm install -g react-native-cli
- gem install xcpretty
script:
- react-native init AwesomeProject
- cd AwesomeProject
- npm install ../
- git apply ../misc/testfairy.patch
- cd android
- "./gradlew assembleRelease"
- cd ../ios
- pod install
- #xcrun xcodebuild -quiet -workspace AwesomeProject.xcworkspace -scheme AwesomeProject -configuration Debug CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO | xcpretty
before_deploy:
- ANDROID_SDK_VERSION=1.11.16
- IOS_VERSION=1.26.1
- cd ../..
- rm -rf AwesomeProject
- sed -i '' "s/\"version\":.*/\"version\":\"${TRAVIS_TAG}\",/g" package.json
- sed -i '' "s/testfairy-android-sdk:.*/testfairy-android-sdk:${ANDROID_SDK_VERSION}@aar'/" android/build.gradle
- curl -s -L https://s3.amazonaws.com/testfairy/sdk/TestFairySDK-${IOS_VERSION}.zip -o TestFairySDK.zip
- unzip -d ios -o TestFairySDK.zip
- rm TestFairySDK.zip
deploy:
  provider: npm
  email: support@testfairy.com
  api_key:
    secure: GqHP9iVVyhC1m0aYBW73+BN4JnHXCMuYfN+fY7AaHr0BCCMrLv9v/7SnByYmKYmco0NkjaytTt/w42PLNEtzznSBHwzOez1JGUUEklWjKGD0d2UNauj6ILzayp10Kn3jzN/iEvS7doF8n9KykkpGCWd2U091qZV8dbGRc+Y8dd42PzCNKtf/B9kZv8mreOfXScz22JFZDizDRRuvjlCYJ8yAVWhmfkZtA4dZyxBPYIvLIW4Hj5Mo99+EVpmotO41OM1K6I0rgeoYK+sMIOP6xTpYLfRXyCUC/5PnolmaSmle9a6L0MgCCntvbHNETwU602h3Ja34c31Z4Eb6FI/iO7FuzpPuZnwAFFfnqjJBkDMx1+TFkX4TrWali9SsXSZc5HGd+1nxciKO5+zn9WFoeSlkM/0sFAVB1N1SqP58fXAmMEwrxTwJDY4LLmcj6lXFYyoeX376TiEvMujaPP74rL1gIKe9Z/VJms623n1aGfEu2ZaVyS3WNA6q8fQRiVAd/HFdXhwCcJYEh6LVwux2mcTZ43bjBmRWwCgPUQNdzEtYdy1q35VetSa27+MXSl/sqRV6elrz/O/+wLAswLw55+aCfTkPm+3IAhQS+zjmMWJ/RDLlEC7lsW9OAYtODvrBdV3Pl/AydtlOqXa4OJ3kGH38/kbZs6heI/75Q2WArqc=
  on:
    tags: true
    repo: testfairy/react-native-testfairy
