name: Build TestFairy for React Native 
on: 
  push:
  schedule:
  - cron:  '0 2 * * *'

jobs:
  build-ios:
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '15.12.0'
    - name: Install Dependencies
      run: |
        npm install -g react-native-cli
        gem install xcpretty
        gem install cocoapods -v 1.10.1
    - name: Create and build sample project with TestFairy
      run: |
        react-native init AwesomeProject
        cd AwesomeProject
        npm install ../
        git apply ../misc/testfairy.patch
        cd ios
        pod install
        set -o pipefail
        xcrun xcodebuild -workspace AwesomeProject.xcworkspace -scheme AwesomeProject -configuration Debug CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO GCC_WARN_INHIBIT_ALL_WARNINGS=YES | xcpretty
  build-android:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '15.12.0'
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
    - name: Install Dependencies
      run: |
        npm install -g react-native-cli
    - name: Create and build sample project with TestFairy
      run: |
        react-native init AwesomeProject
        cd AwesomeProject
        npm install ../
        git apply ../misc/testfairy.patch
        cd android
        ./gradlew --no-daemon assembleRelease
